services:

  # Machine SOURCE : launches ft_nmap
  source:
    build:
      context: .
      dockerfile: Dockerfile.source
    container_name: ft_nmap_source
    networks:
      isolated_net:
        ipv4_address: 192.168.100.10
    volumes:
      - ./:/app
    working_dir: /app
    cap_add:
      - NET_RAW
      - NET_ADMIN
    privileged: true

  # Machine TARGET : to be scanned
  target:
    build:
      context: .
      dockerfile: Dockerfile.target
    container_name: ft_nmap_target
    networks:
      isolated_net:
        ipv4_address: 192.168.100.20
    cap_add:
      - NET_RAW
    privileged: true

networks:
  isolated_net:
    driver: bridge
    # internal: true        # fully isolated, no internet access
    ipam:
      config:
        - subnet: 192.168.100.0/24
          gateway: 192.168.100.1
