FROM alpine:latest

RUN apk add --no-cache \
    # shells & editors
    bash vim \
    # network debug & sniffing
    tcpdump \
    net-tools \
    iproute2 \
    iputils \
    ethtool \
    nmap \
    # connectivity
    curl wget \
    netcat-openbsd \
    socat \
    bind-tools \
    iperf3 \
    # process & system debug
    strace \
    lsof \
    procps \
    htop \
    # real services
    openssh \
    nginx

# SSH setup
RUN ssh-keygen -A \
    && echo "root:root" | chpasswd \
    && sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config \
    && sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config

# nginx setup
RUN mkdir -p /run/nginx

# Ports exposed:
#   Real services : 22 (ssh), 80 (http)
#   socat listeners on well-known ports so getservbyport() returns a name:
#     21   ftp          110  pop3         587  submission   3389 ms-wbt-server
#     23   telnet       119  nntp         631  ipp          5432 postgresql
#     25   smtp         143  imap         993  imaps        5900 vnc
#     53   domain       194  irc          995  pop3s        6379 redis
#     70   gopher       443  https        1194 openvpn      6667 irc
#     79   finger       445  microsoft-ds 1433 ms-sql-s     8080 http-alt
#     88   kerberos     465  smtps        3306 mysql        27017 mongod
EXPOSE 21 22 23 25 26 28 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 53 70 79 80 88 110 119 143 194 443 445 \
       465 587 631 993 995 1194 1433 3306 3389 5432 5900 \
       6379 6667 8080 27017

CMD ["/bin/sh", "-c", "\
  /usr/sbin/sshd && \
  nginx && \
  for port in \
    21 22 23 25 26 28 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 53 70 79 88 \
    110 119 143 194 \
    443 445 465 587 631 \
    993 995 1194 1433 \
    3306 3389 5432 5900 \
    6379 6667 8080 27017; \
  do \
    socat TCP-LISTEN:${port},fork,reuseaddr /dev/null & \
  done; \
  wait \
"]

# ./ft_nmap --ip 192.168.100.20 --port 21,22,23,25,53,70,79,80,88,110,119,143,194,443,445,465,587,631,993,995,1194,1433,3306,3389,5432,5900,6379,6667,8080,27017 --scan SYN | grep "open" | wc -l